#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoBSCKPI.Database.NguoiDung
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BSCKPI")]
	public partial class linqNguoiDungNhomDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqNguoiDungNhomDataContext() : 
				base(global::DaoBSCKPI.Properties.Settings.Default.BSCKPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqNguoiDungNhomDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqNguoiDungNhomDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqNguoiDungNhomDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqNguoiDungNhomDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTNguoiDungNhomTruyNhap_ThongTin")]
		public ISingleResult<sp_tblHTNguoiDungNhomTruyNhap_ThongTinResult> sp_tblHTNguoiDungNhomTruyNhap_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhanVien", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhanVien);
			return ((ISingleResult<sp_tblHTNguoiDungNhomTruyNhap_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTNguoiDungNhomTruyNhap_ThemSua")]
		public int sp_tblHTNguoiDungNhomTruyNhap_ThemSua([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhanVien", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(30)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhanVien, iDNhomTruyNhap, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTNguoiDungNhomTruyNhap_DanhSach")]
		public ISingleResult<sp_tblHTNguoiDungNhomTruyNhap_DanhSachResult> sp_tblHTNguoiDungNhomTruyNhap_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhanVien", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNhanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhanVien);
			return ((ISingleResult<sp_tblHTNguoiDungNhomTruyNhap_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTNguoiDungNhomTruyNhap_Xoa")]
		public int sp_tblHTNguoiDungNhomTruyNhap_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhanVien", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhanVien, iDNhomTruyNhap);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblHTNguoiDungNhomTruyNhap_ThongTinResult
	{
		
		private System.Nullable<System.Guid> _IDNhanVien;
		
		private System.Nullable<int> _IDNhomTruyNhap;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		public sp_tblHTNguoiDungNhomTruyNhap_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhanVien", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDNhanVien
		{
			get
			{
				return this._IDNhanVien;
			}
			set
			{
				if ((this._IDNhanVien != value))
				{
					this._IDNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhomTruyNhap", DbType="Int")]
		public System.Nullable<int> IDNhomTruyNhap
		{
			get
			{
				return this._IDNhomTruyNhap;
			}
			set
			{
				if ((this._IDNhomTruyNhap != value))
				{
					this._IDNhomTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
	}
	
	public partial class sp_tblHTNguoiDungNhomTruyNhap_DanhSachResult
	{
		
		private System.Nullable<System.Guid> _IDNhanVien;
		
		private System.Nullable<int> _IDNhomTruyNhap;
		
		private string _NhomTruyNhap;
		
		public sp_tblHTNguoiDungNhomTruyNhap_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhanVien", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDNhanVien
		{
			get
			{
				return this._IDNhanVien;
			}
			set
			{
				if ((this._IDNhanVien != value))
				{
					this._IDNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhomTruyNhap", DbType="Int")]
		public System.Nullable<int> IDNhomTruyNhap
		{
			get
			{
				return this._IDNhomTruyNhap;
			}
			set
			{
				if ((this._IDNhomTruyNhap != value))
				{
					this._IDNhomTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomTruyNhap", DbType="NVarChar(50)")]
		public string NhomTruyNhap
		{
			get
			{
				return this._NhomTruyNhap;
			}
			set
			{
				if ((this._NhomTruyNhap != value))
				{
					this._NhomTruyNhap = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
