<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqQuyenNhomTruyNhapDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblHTQuyenNhomTruyNhap_Xoa" Method="sp_tblHTQuyenNhomTruyNhap_Xoa">
    <Parameter Name="IDNhomTruyNhap" Parameter="iDNhomTruyNhap" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDQuyenTruyNhap" Parameter="iDQuyenTruyNhap" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChucNang" Parameter="iDChucNang" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblHTQuyenNhomTruyNhap_DanhSach" Method="sp_tblHTQuyenNhomTruyNhap_DanhSach">
    <Parameter Name="IDNhomTruyNhap" Parameter="iDNhomTruyNhap" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblHTQuyenNhomTruyNhap_DanhSachResult">
      <Column Name="IDQuyenTruyNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDNhomTruyNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhomTruyNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDChucNang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChucNang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDQuyenTruyNhap1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuyenTruyNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblHTQuyenNhomTruyNhap_LayQuyen" Method="sp_tblHTQuyenNhomTruyNhap_LayQuyen">
    <Parameter Name="IDNhomTruyNhap" Parameter="iDNhomTruyNhap" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChucNang" Parameter="iDChucNang" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblHTQuyenNhomTruyNhap_LayQuyenResult">
      <Column Name="IDNhomTruyNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDQuyenTruyNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDChucNang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblHTQuyenNhomTruyNhap_ThemSua" Method="sp_tblHTQuyenNhomTruyNhap_ThemSua">
    <Parameter Name="IDNhomTruyNhap" Parameter="iDNhomTruyNhap" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDQuyenTruyNhap" Parameter="iDQuyenTruyNhap" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDChucNang" Parameter="iDChucNang" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
</Database>