#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoBSCKPI.Database.NguoiDung
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BSCKPI")]
	public partial class linqQuyenNhomTruyNhapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqQuyenNhomTruyNhapDataContext() : 
				base(global::DaoBSCKPI.Properties.Settings.Default.BSCKPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqQuyenNhomTruyNhapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqQuyenNhomTruyNhapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqQuyenNhomTruyNhapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqQuyenNhomTruyNhapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTQuyenNhomTruyNhap_Xoa")]
		public int sp_tblHTQuyenNhomTruyNhap_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDQuyenTruyNhap", DbType="Int")] System.Nullable<int> iDQuyenTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChucNang", DbType="Int")] System.Nullable<int> iDChucNang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhomTruyNhap, iDQuyenTruyNhap, iDChucNang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTQuyenNhomTruyNhap_DanhSach")]
		public ISingleResult<sp_tblHTQuyenNhomTruyNhap_DanhSachResult> sp_tblHTQuyenNhomTruyNhap_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhomTruyNhap);
			return ((ISingleResult<sp_tblHTQuyenNhomTruyNhap_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTQuyenNhomTruyNhap_LayQuyen")]
		public ISingleResult<sp_tblHTQuyenNhomTruyNhap_LayQuyenResult> sp_tblHTQuyenNhomTruyNhap_LayQuyen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChucNang", DbType="Int")] System.Nullable<int> iDChucNang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhomTruyNhap, iDChucNang);
			return ((ISingleResult<sp_tblHTQuyenNhomTruyNhap_LayQuyenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblHTQuyenNhomTruyNhap_ThemSua")]
		public int sp_tblHTQuyenNhomTruyNhap_ThemSua([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNhomTruyNhap", DbType="Int")] System.Nullable<int> iDNhomTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDQuyenTruyNhap", DbType="Int")] System.Nullable<int> iDQuyenTruyNhap, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDChucNang", DbType="Int")] System.Nullable<int> iDChucNang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(30)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDNhomTruyNhap, iDQuyenTruyNhap, iDChucNang, nguoiTao);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblHTQuyenNhomTruyNhap_DanhSachResult
	{
		
		private System.Nullable<int> _IDQuyenTruyNhap;
		
		private System.Nullable<int> _IDNhomTruyNhap;
		
		private string _NhomTruyNhap;
		
		private System.Nullable<int> _IDChucNang;
		
		private string _ChucNang;
		
		private System.Nullable<int> _IDQuyenTruyNhap1;
		
		private string _QuyenTruyNhap;
		
		public sp_tblHTQuyenNhomTruyNhap_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyenTruyNhap", DbType="Int")]
		public System.Nullable<int> IDQuyenTruyNhap
		{
			get
			{
				return this._IDQuyenTruyNhap;
			}
			set
			{
				if ((this._IDQuyenTruyNhap != value))
				{
					this._IDQuyenTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhomTruyNhap", DbType="Int")]
		public System.Nullable<int> IDNhomTruyNhap
		{
			get
			{
				return this._IDNhomTruyNhap;
			}
			set
			{
				if ((this._IDNhomTruyNhap != value))
				{
					this._IDNhomTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomTruyNhap", DbType="NVarChar(50)")]
		public string NhomTruyNhap
		{
			get
			{
				return this._NhomTruyNhap;
			}
			set
			{
				if ((this._NhomTruyNhap != value))
				{
					this._NhomTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChucNang", DbType="Int")]
		public System.Nullable<int> IDChucNang
		{
			get
			{
				return this._IDChucNang;
			}
			set
			{
				if ((this._IDChucNang != value))
				{
					this._IDChucNang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucNang", DbType="NVarChar(50)")]
		public string ChucNang
		{
			get
			{
				return this._ChucNang;
			}
			set
			{
				if ((this._ChucNang != value))
				{
					this._ChucNang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyenTruyNhap1", DbType="Int")]
		public System.Nullable<int> IDQuyenTruyNhap1
		{
			get
			{
				return this._IDQuyenTruyNhap1;
			}
			set
			{
				if ((this._IDQuyenTruyNhap1 != value))
				{
					this._IDQuyenTruyNhap1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenTruyNhap", DbType="NVarChar(50)")]
		public string QuyenTruyNhap
		{
			get
			{
				return this._QuyenTruyNhap;
			}
			set
			{
				if ((this._QuyenTruyNhap != value))
				{
					this._QuyenTruyNhap = value;
				}
			}
		}
	}
	
	public partial class sp_tblHTQuyenNhomTruyNhap_LayQuyenResult
	{
		
		private System.Nullable<int> _IDNhomTruyNhap;
		
		private System.Nullable<int> _IDQuyenTruyNhap;
		
		private System.Nullable<int> _IDChucNang;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		public sp_tblHTQuyenNhomTruyNhap_LayQuyenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhomTruyNhap", DbType="Int")]
		public System.Nullable<int> IDNhomTruyNhap
		{
			get
			{
				return this._IDNhomTruyNhap;
			}
			set
			{
				if ((this._IDNhomTruyNhap != value))
				{
					this._IDNhomTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyenTruyNhap", DbType="Int")]
		public System.Nullable<int> IDQuyenTruyNhap
		{
			get
			{
				return this._IDQuyenTruyNhap;
			}
			set
			{
				if ((this._IDQuyenTruyNhap != value))
				{
					this._IDQuyenTruyNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChucNang", DbType="Int")]
		public System.Nullable<int> IDChucNang
		{
			get
			{
				return this._IDChucNang;
			}
			set
			{
				if ((this._IDChucNang != value))
				{
					this._IDChucNang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this._NgayTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this._NguoiTao = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
