<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqChiTieuKPIChoPhongDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblBKChiTieuKPIChoPhong_Them" Method="sp_tblBKChiTieuKPIChoPhong_Them">
    <Parameter Name="Ma" Parameter="ma" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDPhongBan" Parameter="iDPhongBan" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDKPI" Parameter="iDKPI" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblBKChiTieuKPIChoPhong_Xoa" Method="sp_tblBKChiTieuKPIChoPhong_Xoa">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDPhongBan" Parameter="iDPhongBan" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDKPI" Parameter="iDKPI" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblBKChiTieuKPIChoPhong_ThongTin" Method="sp_tblBKChiTieuKPIChoPhong_ThongTin">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDPhongBan" Parameter="iDPhongBan" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDKPI" Parameter="iDKPI" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblBKChiTieuKPIChoPhong_ThongTinResult">
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDDonVi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPhongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDKPI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>